### ISSUE TITLE
How does one start camabc.abs from disk?

### ISSUE THREAD

**Issue by mobluse** [robertjuhasz/camabc#3]
I prepared a disk camabc.dsk and configured ABCWin2 to use ABC80 32K RAM and 80 Cols, and drives UFD-DOS ABC832/834 (MF0-1). I configured it to use camabc.dsk for both MF0 and MF1. Is this correct?

I try to run in ABCWin2 with `run mf0:camabc.abs`, but nothing happens, but there are also no errors. How does one start CamelForth?  
When I do `run mf1:camabc.abs` I get ERR 21. `run camabc` and `run mf0:camabc` also give ERR 21.

I created camabc.dsk in [WSL Ubuntu](https://www.microsoft.com/en-us/store/p/ubuntu/9nblggh4msv6) using:
```
../abc80/abcdisk/ithabs camabc.hex camabc.abs 32768
mkdir camabc
cp camabc.abs camabc/
../abc80/abcdisk/abcwrite abc832 camabc camabc.dsk
```

**Comment by mobluse** [comment]
I got it working now. In ABCWin2 I use disk C:\Program Files (x86)\ABCWin2\disks\80x\ufd631.dsk as MF1: and camabc.dsk as MF0:. Then I do `bye` after start, and enter `camabc`. CamelForth seems to be case sensitive. I use CapsLock. `WORDS` shows commands in Forth.

This helped a bit: http://www.abc80.net/archive/luxor/sw/doc/Anvisning-UFD-DOS.pdf

Video: https://youtu.be/7sdSJXZ3gX8

**Comment by robertjuhasz** [comment]
Yup you got it all right! ;)
