### ISSUE TITLE
Linux script to build dsk (floppy disk image)

### ISSUE THREAD

**Issue by mobluse** [robertjuhasz/camabc#4]
I wonder if you could add this Linux script that does the same as cam.bat. I call it cam.sh:
```
#!/bin/bash
../zxcc-0.5.7/bin/zxcc z80mr camabc
read -n 1 -s -r -p 'Press any key to continue . . .'; echo
../abc80/abcdisk/ithabs camabc.hex camabc.abs 32768
cp camabc.abs camabc/
../abc80/abcdisk/abcwrite abc832 camabc/ camabc.dsk
```

I think a pull request is exaggerated. It should be made executable using `chmod +x cam.sh` and then one can run it using `./cam.sh`. One can also run it using `. cam.sh` without making it executable.

I use it in [WSL Ubuntu](https://blogs.msdn.microsoft.com/commandline/2017/07/10/ubuntu-now-available-from-the-windows-store/).

**Comment by robertjuhasz** [comment]
Done! ;)
